import { memo } from "react";
import Grid from "@mui/material/Grid";
import { Paper, TextField, Typography } from "@mui/material";
import type { Skills, Meta } from "enigma/types/cvBuilder";

interface Props {
    skills: Skills;
    meta: Meta;
    onSkillsListChange: (csv: string) => void;
    onGroupChange: (groupKey: string, csv: string) => void;
    onMetaChange: (k: keyof Meta, v: string) => void;
}

function SkillsMeta({
                               skills, meta, onSkillsListChange, onGroupChange, onMetaChange,
                           }: Props) {
    const csv = (arr: string[]) => (arr || []).join(", ");

    return (
        <Paper elevation={1} sx={{ p: 3, borderRadius: 2, border: "1px solid #E5E7EB" }}>
            <Typography variant="h6" sx={{ mb: 2, color: "#101828" }}>
                Skills & Meta (comma-separated)
            </Typography>

            <Grid container spacing={2}>
                <Grid size={{ xs: 12 }}>
                    <TextField
                        label="Skills"
                        fullWidth
                        value={csv(skills.list)}
                        onChange={(e) => onSkillsListChange(e.target.value)}
                    />
                </Grid>

                {/* Known groups */}
                <Grid size={{ xs: 12, mdx: 4 }}>
                    <TextField
                        label="Languages"
                        fullWidth
                        value={csv(skills.groups["Languages"] || [])}
                        onChange={(e) => onGroupChange("Languages", e.target.value)}
                    />
                </Grid>
                <Grid size={{ xs: 12, mdx: 4 }}>
                    <TextField
                        label="Frameworks"
                        fullWidth
                        value={csv(skills.groups["Frameworks"] || [])}
                        onChange={(e) => onGroupChange("Frameworks", e.target.value)}
                    />
                </Grid>
                <Grid size={{ xs: 12, mdx: 4 }}>
                    <TextField
                        label="Data"
                        fullWidth
                        value={csv(skills.groups["Data"] || [])}
                        onChange={(e) => onGroupChange("Data", e.target.value)}
                    />
                </Grid>

                <Grid size={{ xs: 12, mdx: 6 }}>
                    <TextField
                        label="Meta Position"
                        fullWidth
                        value={meta.position}
                        onChange={(e) => onMetaChange("position", e.target.value)}
                    />
                </Grid>
                <Grid size={{ xs: 12, mdx: 6 }}>
                    <TextField
                        label="Generated By"
                        fullWidth
                        value={meta.generated_by}
                        onChange={(e) => onMetaChange("generated_by", e.target.value)}
                    />
                </Grid>
            </Grid>
        </Paper>
    );
}

export default memo(SkillsMeta);
