on:
  push:
    branches:
      - main
name: Deploy to production on push to `main`

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
      AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
      AUTH_TRUST_HOST: ${{ secrets.AUTH_TRUST_HOST }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Build project
        run: |
          npm i
          npm run build

      - name: Copy standalone builds
        run: |
          mkdir -p .next/standalone/.next
          cp -r .next/static .next/standalone/.next/static
          cp -r public .next/standalone/public 2>/dev/null || true

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.CPANEL_SERVER}}
          username: ${{secrets.CPANEL_USERNAME}}
          password: ${{secrets.CPANEL_PASSWORD}}
          protocol: ${{secrets.CPANEL_PROTOCOL}}
          state-name: .ftp-deploy-sync-state.json
          local-dir: .next/standalone